
## CreateUser

POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
  "name": "John Doe",
  "email": "john.doe2@email.com",
  "password": "12345678@",
  "cep": "01153000"
}
###

## UpdateUser
PATCH http://localhost:8080/user HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe",
  "email": "john.doe2s@email.com",
  "cep": "88132243"
}
###

## GetUserByID
GET http://localhost:8080/user HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
###

## DeleteUser
DELETE http://localhost:8080/user HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
####

## FindManyUsers
GET http://localhost:8080/user/list-all HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
###

## UpdateUserPassword
PATCH http://localhost:8080/user/password HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "password": "123456789@",
  "old_password": "12345678@"
}
###

## Login
# @name login
POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
  "email": "john.doe2@email.com",
  "password": "12345678@"
}
###
@token = {{login.response.body.access_token}}